# Generated by Django 3.2.4 on 2021-06-09 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiTT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TTId', models.CharField(max_length=20, verbose_name='Ký hiệu TT')),
            ],
            options={
                'verbose_name_plural': 'Loại tờ trình',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomID', models.CharField(max_length=30, verbose_name='Ký hiệu phòng')),
            ],
            options={
                'verbose_name_plural': 'Phòng ban',
            },
        ),
        migrations.CreateModel(
            name='ToTrinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoTT', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Số tờ trình')),
                ('TTtitle', models.CharField(max_length=150, verbose_name='Tên tờ trình')),
                ('TTText', models.TextField(blank=True, max_length=500, null=True, verbose_name='Nội dung tóm tắt')),
                ('Creted_on', models.DateField(auto_now_add=True, verbose_name='Ngày lấy số')),
                ('Year', models.CharField(blank=True, editable=False, max_length=4, null=True)),
                ('Count_on_Year', models.CharField(blank=True, max_length=5, null=True)),
                ('Count_on_Room', models.IntegerField(blank=True, null=True)),
                ('RoomId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='CreNumb.room', verbose_name='Phòng')),
                ('TTId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CreNumb.loaitt', verbose_name='Loại tờ trình')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name_plural': 'Tờ trình',
            },
        ),
    ]
